# Generated by Django 4.2.1 on 2023-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='total_venta',
            field=models.IntegerField(editable=False),
        ),
    ]
